[package]
name = "analiza-danych"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minidom = "*"
regex = "1.7.0"

[target.release]
opt-level=3
