spring:
  application:
    name: classification-executor
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/classification-data
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true

config:
  thread-count: 11
  working-directory-path: "/home/czarek/Desktop/analiza-danych/classifier"
  classifier-path: "/home/czarek/Desktop/analiza-danych/classifier/target/release/analiza-danych"
  data-folder: "reuters"
